apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-app
  namespace: demo
spec:
  rules:
  - host: app.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-app
            port:
              number: 80
